version: '3.8'

services:
  aiohttp-basic:
    build: .
    ports:
      - "8080:8080"
    command: python aiohttp_app.py
    container_name: aiohttp_basic_api

  aiohttp-auth:
    build: .
    ports:
      - "8081:8080"
    command: python aiohttp_app_with_auth.py
    container_name: aiohttp_auth_api
